sudo: required
services:
  - docker

before_install:
  - docker build -t jamesmarcoreyes/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesmarcoreyes/docker-react-aws npm run test